[project]
title = "Preswald Project"
version = "0.1.0"
port = "8501"
slug = "my-app-119550"
entrypoint = "hello.py"

[branding]
name = "Air Quality & Health Insights"            
logo = "images/logo.png"                        
favicon = "images/favicon.ico"                  
primaryColor = "#FF2400" 


[data.sample_csv]
type = "csv"
path = "data/sample.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 