name: Deploy Preswald App

on:
  push:
    branches:
      - main  # Run on every push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing updates

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Or whichever version you're using

      - name: Install dependencies
        run: pip install preswald plotly pandas

      - name: Build static site
        run: preswald export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
